reroute:
    enabled: ${MAILER_REROUTING:false}
    recipient: "${MAILER_REROUTE_RECIPIENT}"
    filters:
        internalUsers: '*@bean.qa'

attachment:
    sizeLimit: 20480 # 20MB
    sizeLimitEach: 2048  # 2MB
    allowContentType: [
            'image/jpeg', 'image/jpg', 'image/png', 'image/bmp', 'image/gif', 'image/svg+xml', 'image/tiff',
            'application/pdf', 'text/calendar',
            'text/html',
    ]
