version: "1.0-SNAPSHOT"

# One of: `dev`, `production` or others strings.
env: "${ENV:dev}"

# ---------------------
# Server configuration
# ---------------------
http-server:
  address: ":8484"
  readTimeout:  15s
  writeTimeout: 15s
  idleTimeout: 15s
  graphql:
    introspection: true
    transports:
      post: true
      websocket:
        keepAlivePingInterval: 15s
    playround:
      title: "GraphQL playground"
      enabled: true
      path: /

# ---------------------
# Database connections
# ---------------------
databases:
  master:
    driver: "${DB_DRIVER:sqlite3}"
    url:    "${DB_MASTER_URL:data/db.sqlite}"
  slave:
    driver: "${DB_SLAVE_URL:sqlite3}"
    url:    "${DB_SLAVE_URL:data/db.sqlite}"

# ---------------------
# Beans configuration: Each bean may have its own config
# ---------------------
beans:
  integration:
    s3:
      # Key to encrypt/decrypt the application keys.
      # Length: 16, 24, or 32 bytes -> AES-128, AES-192, AES-256.
      # Change key will make persisted records not accessible.
      key: "${INTEGRATION_S3_KEY:01EBWB516AP6BQD7}"

  # ---------------------
  # Namespace bean
  # ---------------------
  namespace:
    manager:
      maxNumberOfManager: 100

  # ---------------------
  # Access bean
  # ---------------------
  access:
    timeout: "128h"
    # Algorithm is `RS512` because we don't need providing private-key for services to verify the claims.
    # To avoid configuration issues, path to keys should be absolute.
    jwt:
      algorithm: "RS512"
      publicKey: "${JWT_PUBLIC_KEY:resources/keys/id_rsa.pub}"
      privateKey: "${JWT_PRIVATE_KEY:resources/keys/id_rsa}"
      timeout: "${JWT_TIMEOUT:5m}"
