version: "1.0-SNAPSHOT"

# One of: `dev`, `production` or others strings.
env: "${ENV:dev}"

# ---------------------
# Server configuration
# ---------------------
http-server:
    address: ":${PORT:8484}"
    readTimeout: 15s
    writeTimeout: 15s
    idleTimeout: 15s
    graphql:
        introspection: true
        transports:
            post: true
            websocket:
                keepAlivePingInterval: 15s
        playround:
            title: "GraphQL playground"
            enabled: true
            path: /

databases: { $ref: "resources/config/env.${ENV:dev}/databases.yaml" }

bundles:
    space:  { $ref: "resources/config/env.${ENV:dev}/space.yaml" }
    access: { $ref: "resources/config/env.${ENV:dev}/access.yaml" }
    integration:
        s3:     { $ref: "resources/config/env.${ENV:dev}/integration.s3.yaml" }
        mailer: { $ref: "resources/config/env.${ENV:dev}/integration.mailer.yaml" }
