version: "1.0-SNAPSHOT"

http-server:
  address: ":8484"
  readTimeout:  15s
  writeTimeout: 15s
  idleTimeout: 15s
  graphql:
    playround:
      title: "GraphQL playground"
      enabled: true
      path: /

databases:
  default:
    driver: "${DB_DRIVER:sqlite}"
    master:
      url: "${DB_MASTER_URL:dev.sqlite}"
    slave:
      url: "${DB_SLAVE_URL:dev.sqlite}"
