version: "1.0-SNAPSHOT"

http-server:
  address: ":8484"
  readTimeout:  15s
  writeTimeout: 15s
  idleTimeout: 15s
  graphql:
    playround:
      title: "GraphQL playground"
      enabled: true
      path: /

databases:
  master:
    driver: "${DB_DRIVER:sqlite3}"
    url:    "${DB_MASTER_URL:resources/dev.sqlite}"
  slave:
    driver: "${DB_SLAVE_URL:sqlite3}"
    url:    "${DB_SLAVE_URL:resources/dev.sqlite}"

modules:
  access:
    timeout: "128h"
    jwt:
      algorithm: "RS512"
      publicKey: "${JWT_PUBLIC_KEY:resources/keys/id_rsa.pub}"
      privateKey: "${JWT_PRIVATE_KEY:resources/keys/id_rsa}"
      timeout: "${JWT_TIMEOUT:5m}"
