master:
    driver: "${DB_DRIVER:postgres}"
    url: "${DB_MASTER_URL:postgres://postgres:and1bean@127.0.0.1/bean-core?sslmode=disable}"

slave:
    driver: "${DB_SLAVE_URL:postgres}"
    url: "${DB_SLAVE_URL:postgres://postgres:and1bean@127.0.0.1/bean-core?sslmode=disable}"
