on: [ push, pull_request ]
name: "Lint"
jobs:
  lint:
    name: "Run static analysis"
    strategy:
      matrix:
        go-version: [ "1.15.x" ]
        platform: [ "ubuntu-20.04" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 3
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: "go get honnef.co/go/tools/cmd/staticcheck"
      - uses: "actions/checkout@v2.3.4"
      - uses: "actions/cache@v2"
        with:
          path: ~/.cache/staticcheck
          key: staticcheck-${{ github.sha }}
          restore-keys: |
            staticcheck-
      - run: "go vet ./..."
      - run: "$(go env GOPATH)/bin/staticcheck ./..."
