on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 3
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2.3.4
      - run: make dev.test
